### ISSUE TITLE
i cant install deepl

### ISSUE THREAD

**Issue by Eikosa** [0install/0install-dotnet#189]
![image](https://github.com/0install/0install-dotnet/assets/20538090/b082be4d-7fdb-4305-a7c0-72b34e3cc6c9)
![image](https://github.com/0install/0install-dotnet/assets/20538090/ef26e468-c15a-4e4b-adef-60d877e0472f)
it redirects to this page:
https://github.com/0install/0install-dotnet/blob/master/src/Commands/ExitCode.cs
it says my disk is full but this is not the case
![image](https://github.com/0install/0install-dotnet/assets/20538090/3cc67d00-3690-4c51-821e-0c69d7b2a012)

**Comment by bastianeicher** [comment]
Hello @Eikosa,

could you please post the following log files, to help debug the issue:
- `%TEMP%\DeepLSetup %USERNAME% Log.txt`
- `%TEMP%\0install-win %USERNAME% Log.txt`

**Comment by gmxgmxgmx** [comment]
I can't install DEEPL from this path:
[DeepLSetup cb500x Log.txt](https://github.com/0install/0install-dotnet/files/12470080/DeepLSetup.cb500x.Log.txt)

Error Code from Microsoft Store: 0x8A150105

**Comment by bastianeicher** [comment]
@gmxgmxgmx It looks like something is preventing 0install from renaming a directory after extracting files to it. This can sometimes be caused by malware scanners locking files while scanning them. Could you try running the installation again, with any malware scanner except Windows Defender disabled?

**Comment by Eikosa** [comment]
I have solved this problem myself in the past, to be useful to someone else, let me write the solution, you need to fix windows permissions.
