### ISSUE TITLE
Deepl, will no longer install, funny it was installed and working, AI must of saw it as a threat to Microsoft.  Same here, its like they are doing it on purpose

### ISSUE THREAD

**Issue by MrChevere** [0install/0install-dotnet#197]

**Comment by bastianeicher** [comment]
If you’re having problems with the DeepL app, it’s probably best to contact their support about it.

Happy to help with any 0install-specific issues here. Can you perhaps share a screenshot of any error message you may be seeing or describe the problem in more detail?

**Comment by MrChevere** [comment]
Fixed it as always it was bad Microsoft programming!  Thanks!
