### ISSUE TITLE
support zstandard compression

### ISSUE THREAD

**Issue by pmiess** [0install/0install-dotnet#51]
The msys2 project is now compressing packages with zstandard
https://github.com/msys2/MSYS2-packages/pull/1824

if 0install wants feeds from these packages then zstandard compression format support is needed
this includes mingw32 and mingw64 packages

**Comment by bastianeicher** [comment]
Starting with v2.17.3 Zero Install for Windows targets .NET Framework 4.5+ so I should be able to add Zstandard support soon.

**Comment by bastianeicher** [comment]
Implemented in d66166e056356140af35d9bd596e6973c837f62d.

**Comment by bastianeicher** [comment]
Now available in [Zero Install for Windows 2.18.0](https://github.com/0install/0install-win/releases/tag/2.18.0).
