### ISSUE TITLE
support rar archives

### ISSUE THREAD

**Issue by pmiess** [0install/0install-dotnet#56]
Many people post RAR archives of their software .
It would be helpful if I could create feeds for them.

**Comment by bastianeicher** [comment]
I've added SharpCompress for extracting `.tar.lzma`, `.tar.xz` and `.7z` archives in 4f0b7d76f674c1515e71c718488ace094cf0244c. So adding `.rar` support should hopefully be rather easy now.

**Comment by bastianeicher** [comment]
Now available in [Zero Install for Windows 2.18.0](https://github.com/0install/0install-win/releases/tag/2.18.0).
