### ISSUE TITLE
Add More Extension in Context Menu

### ISSUE THREAD

**Issue by archit9169** [0install/0install-dotnet#64]
The context menu does not have an option to include an icon along with other options. 

Proposed: A tag named icon that can be true and false. If true use an icon, icon can be added in the same manner as done in file associations, or use the default executable's icon. If false, do not use an icon.

**Comment by bastianeicher** [comment]
Funnily I just recently implemented something quite similar in c113d5153dbef9928cb4d417bf4008df6043fca8.
This will be included in the next Zero Install for Windows release (probably sometime next week).

This commit adds the feed's or the `<command>`'s icon to the context menu entry. It does not allow you to specify a separate icon specifically for the context menu however. Perhaps I should add that too.

**Comment by archit9169** [comment]
Thanks for that. And also there is not option to assign "directory background" in <target>. VS-Code uses that too, to open the current directory in code.

Currently there are options <target> for "Files", "Directory", "Drive", etc but no "Directory-Background"

**Comment by bastianeicher** [comment]
Great idea! I've missed "those" background context menu entry too. I should be able to have that in the next release.

**Comment by bastianeicher** [comment]
- Context menus for directory background: 1226a2645e64e4f616166824ddd7d30014aad3e7
- Custom icons for context menus + cascading context menus: dd16dfbeaaa59a166719e3a4107124fcf252330f

I'm currently preparing Zero Install for Windows 2.18 which will include these new features.

**Comment by bastianeicher** [comment]
Now available in [Zero Install for Windows 2.18.0](https://github.com/0install/0install-win/releases/tag/2.18.0).

**Comment by archit9169** [comment]
Yeah i saw the commits. But I was wondering can you modify it a bit to include `directories` for only directories and `directories+ `or something for both directories and background? Because in certain use cases some apps might require only one of these actions. Like vlc or some other media player can have context menu entry for directories but not for background while vs code has both.

**Comment by archit9169** [comment]
#70
